name: Scheduled Notebook Runner

on:
  schedule:
    # runs every hour – change this cron as you like
    - cron: '0 * * * *'
    # add this so you can trigger it by button
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ── 3.2 Install Jupyter/nbconvert + register python3 kernel ──────────
      - name: Install nbconvert & ipykernel
        run: |
          pip install --quiet nbconvert ipykernel
          # Register a kernel called "python3" so nbconvert --execute can find it
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      # ── 3.3 Run the runner script ────────────────────────────────────────
      - name: Execute notebooks
        run: python run_all.py

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add notebooks/*.ipynb
          git commit -m "Scheduled run: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
